CONFDIR = $(SRCDIR)/config

#### User configuration:

# The executables are put in $(BDIR). See also "make symlinks" in the
# config directory.

#BDIR = /usr/local/bin
BDIR = $(SRCDIR)/bin

# Shared libraries, if built, go here, as do regular .a libraries, and
# a few scripts.

#LIBDIR = /usr/local/lib
LIBDIR = $(SRCDIR)/lib

# Set this to switch between .a libraries and .so files.

LIBEXT = a
#LIBEXT = so

# Whether to use OpenMP.

OMP_FLAG = -fopenmp

# Which version of BLAS.

BLAS = -lgslcblas -L/usr/local/GSL/gcc-9.2.0/2.6/lib

# Optimize GLS.

OGSL = -DHAVE_INLINE=1 -DGSL_RANGE_CHECK_OFF=1

# Whether to use GIFTI. The location can be overriden
# in Makefile.site, or here.

#HAVE_GIFTI = 1
#GIFTIFLAGS = -I/usr/include/gifti -I/usr/include/nifti
#GIFTILIBS = -lgiftiio
