# Create either a static or shared lib, depending on $(LIBEXT)

TARGET = $(LIB).$(LIBEXT)
INC = $(shell ls $(SRCDIR)/include/*.h)

all: $(TARGET)

$(OBJ): $(INC)

$(LIB).a: $(OBJ)
	$(AR) crs $@ $(OBJ)
	@mkdir -p $(LIBDIR)
	@rm -f $(LIBDIR)/$(LIB).so
	cp $@ $(LIBDIR)

$(LIB).so: $(OBJ)
	$(CC) -o $@ -shared $(OBJ)
	@mkdir -p $(LIBDIR)
	@rm -f $(LIBDIR)/$(LIB).a
	cp $@ $(LIBDIR)
